parameters:
  sonata.chunks.storage.filesystem.class: Kolyadin\SonataMediaChunkUploader\Storage\FilesystemStorage

services:
  Kolyadin\SonataMediaChunkUploader\Service\ChunkService: '@sonata.chunks.service'

  sonata.chunks.service:
    class: Kolyadin\SonataMediaChunkUploader\Service\ChunkService
    public: true
    autowire: true
    arguments:
      - "%sonata.chunks.settings%"
      - "@sonata.chunks.storage"

  sonata.chunks.form.large_media:
    class: Kolyadin\SonataMediaChunkUploader\Form\Type\LargeMediaType
    arguments: ['@sonata.media.pool', "%sonata.media.media.class%"]
    tags: [form.type]

  sonata.media.provider.large_file:
    class: Kolyadin\SonataMediaChunkUploader\Provider\LargeFileProvider
    tags:
      - { name: sonata.media.provider }
    arguments:
      - 'sonata.media.provider.large_file'
      - '@sonata.media.filesystem.local'
      - '@sonata.media.cdn.server'
      - '@sonata.media.generator.default'
      - '@sonata.media.thumbnail.format'
      - '%sonata.media.adapter.filesystem.local.path%'
      - []
      - []
    calls:
      - [ setTemplates, [ { helper_thumbnail: "@@SonataMedia/Provider/thumbnail.html.twig", helper_view: "@@SonataMedia/Provider/view_file.html.twig" } ]]
